#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xcb-util-keysyms
Version  : 0.4.0
Release  : 9
URL      : http://xcb.freedesktop.org/dist/xcb-util-keysyms-0.4.0.tar.gz
Source0  : http://xcb.freedesktop.org/dist/xcb-util-keysyms-0.4.0.tar.gz
Summary  : XCB Keysyms
Group    : Development/Tools
License  : MIT
Requires: xcb-util-keysyms-lib
BuildRequires : doxygen
BuildRequires : graphviz
BuildRequires : libxcb-dev
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
About XCB util modules
======================
The XCB util modules provides a number of libraries which sit on top
of libxcb, the core X protocol library, and some of the extension
libraries. These experimental libraries provide convenience functions
and interfaces which make the raw X protocol more usable. Some of the
libraries also provide client-side code which is not strictly part of
the X protocol but which have traditionally been provided by Xlib.

%package dev
Summary: dev components for the xcb-util-keysyms package.
Group: Development
Requires: xcb-util-keysyms-lib
Provides: xcb-util-keysyms-devel

%description dev
dev components for the xcb-util-keysyms package.


%package lib
Summary: lib components for the xcb-util-keysyms package.
Group: Libraries

%description lib
lib components for the xcb-util-keysyms package.


%prep
%setup -q -n xcb-util-keysyms-0.4.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xcb/xcb_keysyms.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
